export const tickets = [
  {
    id: 1,
    title: "Fix Login Bug",
    description:
      "Resolve the login issue preventing some users from accessing their accounts.",
    project: {
      _id: 1,
      name: "E-Commerce Platform Development",
      shortDescription: "Develop a new e-commerce platform.",
      priority: "High",
    },
    assignedDev: {
      _id: 7,
      name: "Developer One",
    },
    priority: "High",
    deadline: "2024-07-01",
  },
  {
    id: 2,
    title: "Add Payment Gateway",
    description: "Integrate a new payment gateway for more payment options.",
    project: {
      _id: 1,
      name: "E-Commerce Platform Development",
      shortDescription: "Develop a new e-commerce platform.",
      priority: "High",
    },
    assignedDev: {
      _id: 7,
      name: "Developer One",
    },
    priority: "Medium",
    deadline: "2024-07-05",
  },
  {
    id: 3,
    title: "Update User Dashboard",
    description:
      "Revamp the user dashboard with a new design and additional features.",
    project: {
      _id: 1,
      name: "E-Commerce Platform Development",
      shortDescription: "Develop a new e-commerce platform.",
      priority: "High",
    },
    assignedDev: {
      _id: 8,
      name: "Developer Two",
    },
    priority: "Low",
    deadline: "2024-07-10",
  },
  {
    id: 4,
    title: "Optimize Database Queries",
    description:
      "Improve the performance of database queries to speed up the application.",
    project: {
      _id: 1,
      name: "E-Commerce Platform Development",
      shortDescription: "Develop a new e-commerce platform.",
      priority: "High",
    },
    assignedDev: {
      _id: 8,
      name: "Developer Two",
    },
    priority: "High",
    deadline: "2024-07-15",
  },
  {
    id: 5,
    title: "Implement 2FA",
    description: "Add two-factor authentication for enhanced security.",
    project: {
      _id: 2,
      name: "Company Website Redesign",
      shortDescription: "Redesign the company website.",
      priority: "Medium",
    },
    assignedDev: {
      _id: 9,
      name: "Developer Three",
      role: "Developer",
    },
    priority: "Medium",
    deadline: "2024-07-20",
  },
  {
    id: 6,
    title: "Design New Landing Page",
    description: "Create a new landing page for the upcoming product launch.",
    project: {
      _id: 2,
      name: "Company Website Redesign",
      shortDescription: "Redesign the company website.",
      priority: "Medium",
    },
    assignedDev: {
      _id: 9,
      name: "Developer Three",
      role: "Developer",
    },
    priority: "Low",
    deadline: "2024-07-25",
  },
  {
    id: 7,
    title: "Fix Mobile Responsiveness",
    description:
      "Ensure that the website is fully responsive on mobile devices.",
    project: {
      _id: 2,
      name: "Company Website Redesign",
      shortDescription: "Redesign the company website.",
      priority: "Medium",
    },
    assignedDev: {
      _id: 10,
      name: "Developer Four",
      role: "Developer",
    },
    priority: "High",
    deadline: "2024-07-30",
  },
  {
    id: 8,
    title: "Add User Role Management",
    description: "Implement user role management functionality for admins.",
    project: {
      _id: 2,
      name: "Company Website Redesign",
      shortDescription: "Redesign the company website.",
      priority: "Medium",
    },
    assignedDev: {
      _id: 10,
      name: "Developer Four",
      role: "Developer",
    },
    priority: "Medium",
    deadline: "2024-08-01",
  },
  {
    id: 9,
    title: "Integrate Chat Support",
    description:
      "Add live chat support to the website for real-time customer assistance.",
    project: {
      _id: 3,
      name: "Customer Feedback System",
      shortDescription: "Implement a customer feedback system.",
      priority: "Low",
    },
    assignedDev: {
      _id: 11,
      name: "Developer Five",
      role: "Developer",
    },
    priority: "Low",
    deadline: "2024-08-05",
  },
  {
    id: 10,
    title: "Refactor Codebase",
    description:
      "Refactor the existing codebase to improve maintainability and performance.",
    project: {
      _id: 3,
      name: "Customer Feedback System",
      shortDescription: "Implement a customer feedback system.",
      priority: "Low",
    },
    assignedDev: {
      _id: 11,
      name: "Developer Five",
      role: "Developer",
    },
    priority: "High",
    deadline: "2024-08-10",
  },
  {
    id: 11,
    title: "Set Up CI/CD Pipeline",
    description:
      "Implement a continuous integration and continuous deployment pipeline.",
    project: {
      _id: 3,
      name: "Customer Feedback System",
      shortDescription: "Implement a customer feedback system.",
      priority: "Low",
    },
    assignedDev: {
      _id: 12,
      name: "Developer Six",
      role: "Developer",
    },
    priority: "Medium",
    deadline: "2024-08-15",
  },
  {
    id: 12,
    title: "Enhance SEO",
    description:
      "Optimize the website for search engines to improve visibility.",
    project: {
      _id: 3,
      name: "Customer Feedback System",
      shortDescription: "Implement a customer feedback system.",
      priority: "Low",
    },
    assignedDev: {
      _id: 12,
      name: "Developer Six",
      role: "Developer",
    },
    priority: "Low",
    deadline: "2024-08-20",
  },
  {
    id: 13,
    title: "Fix Broken Links",
    description: "Identify and fix all broken links on the website.",
    project: {
      _id: 4,
      name: "Network Infrastructure Upgrade",
      shortDescription: "Upgrade internal network infrastructure.",
      priority: "High",
    },
    assignedDev: {
      _id: 13,
      name: "Developer Seven",
      role: "Developer",
    },
    priority: "High",
    deadline: "2024-08-25",
  },
  {
    id: 14,
    title: "Update Privacy Policy",
    description: "Revise the privacy policy to comply with new regulations.",
    project: {
      _id: 4,
      name: "Network Infrastructure Upgrade",
      shortDescription: "Upgrade internal network infrastructure.",
      priority: "High",
    },
    assignedDev: {
      _id: 13,
      name: "Developer Seven",
      role: "Developer",
    },
    priority: "Medium",
    deadline: "2024-08-30",
  },
  {
    id: 15,
    title: "Implement Dark Mode",
    description: "Add a dark mode option for the website.",
    project: {
      _id: 4,
      name: "Network Infrastructure Upgrade",
      shortDescription: "Upgrade internal network infrastructure.",
      priority: "High",
    },
    assignedDev: {
      _id: 14,
      name: "Developer Eight",
      role: "Developer",
    },
    priority: "Low",
    deadline: "2024-09-01",
  },
  {
    id: 16,
    title: "Improve Accessibility",
    description: "Ensure the website is accessible to users with disabilities.",
    project: {
      _id: 4,
      name: "Network Infrastructure Upgrade",
      shortDescription: "Upgrade internal network infrastructure.",
      priority: "High",
    },
    assignedDev: {
      _id: 14,
      name: "Developer Eight",
      role: "Developer",
    },
    priority: "High",
    deadline: "2024-09-05",
  },
  {
    id: 17,
    title: "Add Social Media Sharing",
    description: "Implement social media sharing functionality.",
    project: {
      _id: 5,
      name: "Mobile Application Development",
      shortDescription: "Develop a mobile application.",
      priority: "Medium",
    },
    assignedDev: {
        _id: 15,
        name: "Developer Nine",
        role: "Developer",
    },
    priority: "Medium",
    deadline: "2024-09-10",
  },
  {
    id: 18,
    title: "Fix Logout Issue",
    description:
      "Resolve the issue causing some users to be unable to log out.",
    project: {
      _id: 5,
      name: "Mobile Application Development",
      shortDescription: "Develop a mobile application.",
      priority: "Medium",
    },
    assignedDev: {
        _id: 15,
        name: "Developer Nine",
        role: "Developer",
    },
    priority: "Low",
    deadline: "2024-09-15",
  },
  {
    id: 19,
    title: "Add Push Notifications",
    description: "Implement push notifications for important updates.",
    project: {
      _id: 5,
      name: "Mobile Application Development",
      shortDescription: "Develop a mobile application.",
      priority: "Medium",
    },
    assignedDev: {
        _id: 16,
        name: "Developer Ten",
        role: "Developer",
    },
    priority: "High",
    deadline: "2024-09-20",
  },
  {
    id: 20,
    title: "Set Up Analytics",
    description: "Integrate an analytics tool to track user behavior.",
    project: {
      _id: 5,
      name: "Mobile Application Development",
      shortDescription: "Develop a mobile application.",
      priority: "Medium",
    },
    assignedDev: {
        _id: 16,
        name: "Developer Ten",
        role: "Developer",
    },
    priority: "Medium",
    deadline: "2024-09-25",
  },
  {
    id: 21,
    title: "Fix Cart Issues",
    description: "Resolve issues with the shopping cart functionality.",
    project: {
      _id: 6,
      name: "Marketing Campaign Launch",
      shortDescription: "Launch a new marketing campaign.",
      priority: "Low",
    },
    assignedDev: {
        _id: 17,
        name: "Developer Eleven",
        role: "Developer",
    },
    priority: "Low",
    deadline: "2024-09-30",
  },
  {
    id: 22,
    title: "Improve Site Speed",
    description: "Optimize the website to load faster.",
    project: {
      _id: 6,
      name: "Marketing Campaign Launch",
      shortDescription: "Launch a new marketing campaign.",
      priority: "Low",
    },
    assignedDev: {
        _id: 17,
        name: "Developer Eleven",
        role: "Developer",
    },
    priority: "High",
    deadline: "2024-10-01",
  },
  {
    id: 23,
    title: "Update User Profile Page",
    description: "Enhance the user profile page with new features.",
    project: {
      _id: 6,
      name: "Marketing Campaign Launch",
      shortDescription: "Launch a new marketing campaign.",
      priority: "Low",
    },
    assignedDev: {
        _id: 18,
        name: "Developer Twelve",
        role: "Developer",
    },
    priority: "Medium",
    deadline: "2024-10-05",
  },
  {
    id: 24,
    title: "Fix Image Upload Bug",
    description: "Resolve the issue preventing image uploads.",
    project: {
      _id: 6,
      name: "Marketing Campaign Launch",
      shortDescription: "Launch a new marketing campaign.",
      priority: "Low",
    },
    assignedDev: {
        _id: 18,
        name: "Developer Twelve",
        role: "Developer",
    },
    priority: "Low",
    deadline: "2024-10-10",
  },
  {
    id: 25,
    title: "Implement Email Verification",
    description: "Add email verification for new user registrations.",
    project: {
      _id: 7,
      name: "Payment Gateway Integration",
      shortDescription: "Integrate third-party payment gateways.",
      priority: "High",
    },
    assignedDev: {
        _id: 19,
        name: "Developer Thirteen",
        role: "Developer",
    },
    priority: "High",
    deadline: "2024-10-15",
  },
  {
    id: 26,
    title: "Add Multi-language Support",
    description: "Implement support for multiple languages.",
    project: {
      _id: 7,
      name: "Payment Gateway Integration",
      shortDescription: "Integrate third-party payment gateways.",
      priority: "High",
    },
    assignedDev: {
        _id: 19,
        name: "Developer Thirteen",
        role: "Developer",
    },
    priority: "Medium",
    deadline: "2024-10-20",
  },
  {
    id: 27,
    title: "Fix Password Reset Bug",
    description: "Resolve the issue preventing password resets.",
    project: {
      _id: 7,
      name: "Payment Gateway Integration",
      shortDescription: "Integrate third-party payment gateways.",
      priority: "High",
    },
    assignedDev: {
        _id: 20,
        name: "Developer Fourteen",
        role: "Developer",
    },
    priority: "Low",
    deadline: "2024-10-25",
  },
  {
    id: 28,
    title: "Improve Search Functionality",
    description: "Enhance the search functionality for better results.",
    project: {
      _id: 7,
      name: "Payment Gateway Integration",
      shortDescription: "Integrate third-party payment gateways.",
      priority: "High",
    },
    assignedDev: {
        _id: 20,
        name: "Developer Fourteen",
        role: "Developer",
    },
    priority: "High",
    deadline: "2024-10-30",
  },
  {
    id: 29,
    title: "Implement User Activity Log",
    description: "Add logging for user activities for auditing purposes.",
    project: {
      _id: 8,
      name: "Data Migration to New Server",
      shortDescription: "Migrate data to new server.",
      priority: "Medium",
    },
    assignedDev: {
        _id: 21,
        name: "Developer Fifteen",
        role: "Developer",
    },
    priority: "Medium",
    deadline: "2024-11-01",
  },
  {
    id: 30,
    title: "Fix Registration Bug",
    description: "Resolve the issue causing errors during user registration.",
    project: {
      _id: 8,
      name: "Data Migration to New Server",
      shortDescription: "Migrate data to new server.",
      priority: "Medium",
    },
    assignedDev: {
        _id: 21,
        name: "Developer Fifteen",
        role: "Developer",
    },
    priority: "Low",
    deadline: "2024-11-05",
  },
  {
    id: 31,
    title: "Update API Documentation",
    description: "Revise and update the API documentation.",
    project: {
      _id: 8,
      name: "Data Migration to New Server",
      shortDescription: "Migrate data to new server.",
      priority: "Medium",
    },
    assignedDev: {
        _id: 22,
        name: "Developer Sixteen",
        role: "Developer",
    },
    priority: "High",
    deadline: "2024-11-10",
  },
  {
    id: 32,
    title: "Add Rate Limiting",
    description: "Implement rate limiting to prevent abuse of the API.",
    project: {
      _id: 8,
      name: "Data Migration to New Server",
      shortDescription: "Migrate data to new server.",
      priority: "Medium",
    },
    assignedDev: {
        _id: 22,
        name: "Developer Sixteen",
        role: "Developer",
    },
    priority: "Medium",
    deadline: "2024-11-15",
  },
  {
    id: 33,
    title: "Fix File Download Bug",
    description: "Resolve the issue preventing file downloads.",
    project: {
      _id: 9,
      name: "Security Protocols Implementation",
      shortDescription: "Implement new security protocols.",
      priority: "High",
    },
    assignedDev: {
        _id: 23,
        name: "Developer Seventeen",
        role: "Developer",
    },
    priority: "Low",
    deadline: "2024-11-20",
  },
  {
    id: 34,
    title: "Improve Email Template",
    description: "Enhance the design and content of email templates.",
    project: {
      _id: 9,
      name: "Security Protocols Implementation",
      shortDescription: "Implement new security protocols.",
      priority: "High",
    },
    assignedDev: {
        _id: 23,
        name: "Developer Seventeen",
        role: "Developer",
    },
    priority: "High",
    deadline: "2024-11-25",
  },
  {
    id: 35,
    title: "Add Admin Dashboard",
    description: "Create an admin dashboard for managing users and content.",
    project: {
      _id: 9,
      name: "Security Protocols Implementation",
      shortDescription: "Implement new security protocols.",
      priority: "High",
    },
    assignedDev: {
        _id: 24,
        name: "Developer Eighteen",
        role: "Developer",
    },
    priority: "Medium",
    deadline: "2024-11-30",
  },
  {
    id: 36,
    title: "Fix Notification Bug",
    description: "Resolve the issue with notifications not being sent.",
    project: {
      _id: 9,
      name: "Security Protocols Implementation",
      shortDescription: "Implement new security protocols.",
      priority: "High",
    },
    assignedDev: {
        _id: 24,
        name: "Developer Eighteen",
        role: "Developer",
    },
    priority: "Low",
    deadline: "2024-12-01",
  },
  {
    id: 37,
    title: "Improve Error Handling",
    description: "Enhance error handling throughout the application.",
    project: {
      _id: 10,
      name: "Employee Training Program",
      shortDescription: "Develop employee training and development program.",
      priority: "Low",
    },
    assignedDev: {
        _id: 25,
        name: "Developer Nineteen",
        role: "Developer",
    },
    priority: "High",
    deadline: "2024-12-05",
  },
  {
    id: 38,
    title: "Add User Analytics",
    description: "Implement analytics to track user behavior and engagement.",
    project: {
      _id: 10,
      name: "Employee Training Program",
      shortDescription: "Develop employee training and development program.",
      priority: "Low",
    },
    assignedDev: {
        _id: 25,
        name: "Developer Nineteen",
        role: "Developer",
    },
    priority: "Medium",
    deadline: "2024-12-10",
  },
  {
    id: 39,
    title: "Fix Video Playback Bug",
    description: "Resolve the issue preventing video playback on some devices.",
    project: {
      _id: 10,
      name: "Employee Training Program",
      shortDescription: "Develop employee training and development program.",
      priority: "Low",
    },
    assignedDev: {
        _id: 26,
        name: "Developer Twenty",
        role: "Developer",
    },
    priority: "Low",
    deadline: "2024-12-15",
  },
  {
    id: 40,
    title: "Implement File Upload",
    description: "Add file upload functionality to the user profile.",
    project: {
      _id: 10,
      name: "Employee Training Program",
      shortDescription: "Develop employee training and development program.",
      priority: "Low",
    },
    assignedDev: {
        _id: 26,
        name: "Developer Twenty",
        role: "Developer",
    },
    priority: "High",
    deadline: "2024-12-20",
  },
  {
    id: 41,
    title: "Fix Logout Redirect",
    description: "Resolve the issue causing incorrect redirects on logout.",
    project: {
      _id: 1,
      name: "E-Commerce Platform Development",
      shortDescription: "Develop a new e-commerce platform.",
      priority: "High",
    },
    assignedDev: {
        _id: 27,
        name: "Developer Twenty-One",
        role: "Developer",
    },
    priority: "Medium",
    deadline: "2024-12-25",
  },
  {
    id: 42,
    title: "Improve Logging",
    description: "Enhance logging for better debugging and monitoring.",
    project: {
      _id: 1,
      name: "E-Commerce Platform Development",
      shortDescription: "Develop a new e-commerce platform.",
      priority: "High",
    },
    assignedDev: {
        _id: 27,
        name: "Developer Twenty-One",
        role: "Developer",
    },
    priority: "Low",
    deadline: "2024-12-30",
  },
  {
    id: 43,
    title: "Add CAPTCHA to Forms",
    description: "Implement CAPTCHA to prevent automated form submissions.",
    project: {
      _id: 2,
      name: "Company Website Redesign",
      shortDescription: "Redesign the company website.",
      priority: "Medium",
    },
    assignedDev: {
        _id: 28,
        name: "Developer Twenty-Two",
        role: "Developer",
    },
    priority: "High",
    deadline: "2024-12-31",
  },
  {
    id: 44,
    title: "Fix Broken Styles",
    description: "Resolve issues with broken styles in the mobile view.",
    project: {
      _id: 2,
      name: "Company Website Redesign",
      shortDescription: "Redesign the company website.",
      priority: "Medium",
    },
    assignedDev: {
        _id: 28,
        name: "Developer Twenty-Two",
        role: "Developer",
    },
    priority: "Medium",
    deadline: "2024-12-31",
  },
  {
    id: 45,
    title: "Add User Onboarding",
    description: "Create an onboarding process for new users.",
    project: {
      _id: 3,
      name: "Customer Feedback System",
      shortDescription: "Implement a customer feedback system.",
      priority: "Low",
    },
    assignedDev: {
        _id: 29,
        name: "Developer Twenty-Three",
        role: "Developer",
    },
    priority: "Low",
    deadline: "2025-01-05",
  },
  {
    id: 46,
    title: "Fix Language Switcher Bug",
    description:
      "Resolve the issue preventing the language switcher from working.",
    project: {
      _id: 3,
      name: "Customer Feedback System",
      shortDescription: "Implement a customer feedback system.",
      priority: "Low",
    },
    assignedDev: {
        _id: 29,
        name: "Developer Twenty-Three",
        role: "Developer",
    },
    priority: "High",
    deadline: "2025-01-10",
  },
  {
    id: 47,
    title: "Implement SSO",
    description: "Add single sign-on functionality for enterprise users.",
    project: {
      _id: 4,
      name: "Network Infrastructure Upgrade",
      shortDescription: "Upgrade internal network infrastructure.",
      priority: "High",
    },
    assignedDev: {
        _id: 30,
        name: "Developer Twenty-Four",
        role: "Developer",
    },
    priority: "Medium",
    deadline: "2025-01-15",
  },
  {
    id: 48,
    title: "Fix Date Formatting",
    description:
      "Resolve issues with incorrect date formatting across the app.",
    project: {
      _id: 4,
      name: "Network Infrastructure Upgrade",
      shortDescription: "Upgrade internal network infrastructure.",
      priority: "High",
    },
    assignedDev: {
        _id: 30,
        name: "Developer Twenty-Four",
        role: "Developer",
    },
    priority: "Low",
    deadline: "2025-01-20",
  },
  {
    id: 49,
    title: "Enhance Security",
    description: "Add additional security measures to protect user data.",
    project: {
      _id: 5,
      name: "Mobile Application Development",
      shortDescription: "Develop a mobile application.",
      priority: "Medium",
    },
    assignedDev: {
        _id: 31,
        name: "Developer Twenty-Five",
        role: "Developer",
    },
    priority: "High",
    deadline: "2025-01-25",
  },
  {
    id: 50,
    title: "Update Terms of Service",
    description: "Revise the terms of service to reflect new policies.",
    project: {
      _id: 5,
      name: "Mobile Application Development",
      shortDescription: "Develop a mobile application.",
      priority: "Medium",
    },
    assignedDev: {
        _id: 31,
        name: "Developer Twenty-Five",
        role: "Developer",
    },
    priority: "Medium",
    deadline: "2025-01-30",
  },
  {
    id: 51,
    title: "Fix Pagination Bug",
    description:
      "Resolve the issue causing pagination errors in the user list.",
    project: {
      _id: 6,
      name: "Marketing Campaign Launch",
      shortDescription: "Launch a new marketing campaign.",
      priority: "Low",
    },
    assignedDev: {
        _id: 32,
        name: "Developer Twenty-Six",
        role: "Developer",
    },
    priority: "Low",
    deadline: "2025-02-01",
  },
  {
    id: 52,
    title: "Add User Analytics",
    description: "Implement user analytics to track engagement and activity.",
    project: {
      _id: 6,
      name: "Marketing Campaign Launch",
      shortDescription: "Launch a new marketing campaign.",
      priority: "Low",
    },
    assignedDev: {
        _id: 32,
        name: "Developer Twenty-Six",
        role: "Developer",
    },
    priority: "High",
    deadline: "2025-02-05",
  },
  {
    id: 53,
    title: "Fix Email Sending Issue",
    description: "Resolve the issue preventing emails from being sent.",
    project: {
      _id: 7,
      name: "Payment Gateway Integration",
      shortDescription: "Integrate third-party payment gateways.",
      priority: "High",
    },
    assignedDev: {
        _id: 33,
        name: "Developer Twenty-Seven",
        role: "Developer",
    },
    priority: "Medium",
    deadline: "2025-02-10",
  },
  {
    id: 54,
    title: "Add User Import",
    description: "Implement functionality to import users from a CSV file.",
    project: {
      _id: 7,
      name: "Payment Gateway Integration",
      shortDescription: "Integrate third-party payment gateways.",
      priority: "High",
    },
    assignedDev: {
        _id: 33,
        name: "Developer Twenty-Seven",
        role: "Developer",
    },
    priority: "Low",
    deadline: "2025-02-15",
  },
  {
    id: 55,
    title: "Fix CSS Issues",
    description: "Resolve various CSS issues affecting the layout.",
    project: {
      _id: 8,
      name: "Data Migration to New Server",
      shortDescription: "Migrate data to new server.",
      priority: "Medium",
    },
    assignedDev: {
        _id: 34,
        name: "Developer Twenty-Eight",
        role: "Developer",
    },
    priority: "High",
    deadline: "2025-02-20",
  },
  {
    id: 56,
    title: "Add Audit Logs",
    description: "Implement audit logs to track changes and actions.",
    project: {
      _id: 8,
      name: "Data Migration to New Server",
      shortDescription: "Migrate data to new server.",
      priority: "Medium",
    },
    assignedDev: {
        _id: 34,
        name: "Developer Twenty-Eight",
        role: "Developer",
    },
    priority: "Medium",
    deadline: "2025-02-25",
  },
  {
    id: 57,
    title: "Fix Time Zone Issues",
    description: "Resolve issues with time zones affecting event times.",
    project: {
      _id: 9,
      name: "Security Protocols Implementation",
      shortDescription: "Implement new security protocols.",
      priority: "High",
    },
    assignedDev: {
        _id: 35,
        name: "Developer Twenty-Nine",
        role: "Developer",
    },
    priority: "Low",
    deadline: "2025-03-01",
  },
  {
    id: 58,
    title: "Add API Rate Limiting",
    description: "Implement rate limiting on the API to prevent abuse.",
    project: {
      _id: 9,
      name: "Security Protocols Implementation",
      shortDescription: "Implement new security protocols.",
      priority: "High",
    },
    assignedDev: {
        _id: 35,
        name: "Developer Twenty-Nine",
        role: "Developer",
    },
    priority: "High",
    deadline: "2025-03-05",
  },
  {
    id: 59,
    title: "Fix Search Indexing",
    description:
      "Resolve issues with search indexing causing slow search results.",
    project: {
      _id: 10,
      name: "Employee Training Program",
      shortDescription: "Develop employee training and development program.",
      priority: "Low",
    },
    assignedDev: {
        _id: 36,
        name: "Developer Thirty",
        role: "Developer",
    },
    priority: "Medium",
    deadline: "2025-03-10",
  },
  {
    id: 60,
    title: "Add User Reports",
    description:
      "Implement user reporting functionality to track user activity.",
    project: {
      _id: 10,
      name: "Employee Training Program",
      shortDescription: "Develop employee training and development program.",
      priority: "Low",
    },
    assignedDev: {
        _id: 36,
        name: "Developer Thirty",
        role: "Developer",
    },
    priority: "Low",
    deadline: "2025-03-15",
  },
];

export const getAllTickets = function() {
  return tickets;
}
